# Generated by Django 5.2.1 on 2026-06-18 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_used_hrs', models.FloatField(default=0)),
                ('total_miles', models.FloatField(default=0)),
                ('total_drive_hours', models.FloatField(default=0)),
                ('route_geometry', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('mile_marker', models.FloatField(default=0)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('arrival', models.DateTimeField()),
                ('departure', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.trip')),
            ],
            options={
                'ordering': ['arrival'],
            },
        ),
        migrations.CreateModel(
            name='LogDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('segments', models.JSONField(default=list)),
                ('totals', models.JSONField(default=dict)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.trip')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
