# Generated by Django 5.2.1 on 2026-06-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='violations',
            field=models.JSONField(default=list),
        ),
    ]
