# Generated by Django 5.2.1 on 2026-06-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trip_violations'),
    ]

    operations = [
        migrations.AddField(
            model_name='logday',
            name='driving_miles',
            field=models.FloatField(default=0),
        ),
    ]
